### ISSUE TITLE
ANSI control codes should (maybe?) have zero width

### ISSUE THREAD

**Issue by rofrankel** [imRobots/wcwidth#1]
I think ANSI control codes - like those used by [ansicolor](https://pub.dev/packages/ansicolor)- should have zero width.

(I initially filed [an issue](https://github.com/yuzumone/tabler/issues/5) on the [tabler](https://github.com/yuzumone/tabler) package, but when I took a look at the code I realized that it uses this library for the relevant computation.  See that issue for more detail/context.)

**Comment by lu2xin** [comment]
ANSI control codes ( eg: "\u{001B}[32m",  set foreground color to green ) should be parsed instead of calculate width
